name: Build Base Alpine Images for EasySwoole

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - 'main'

jobs:
  build_base_alpine_images:
    runs-on: ubuntu-22.04
    if: github.repository == 'xuesilf/easyswoole-docker'
    name: The Base Alpine Image For EasySwoole

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image easyswoolexuesi2021/php:7.3.33-alpine3.12-base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/php8/8.1.22/alpine/3.16/base/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            easyswoolexuesi2021/php:8.1.22-alpine3.16-base
