name: Build Versioned Alpine Images for EasySwoole php82

#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build_versioned_alpine_images:
    runs-on: ubuntu-22.04
    if: github.repository == 'xuesilf/easyswoole-docker'
    name: The Alpine Image For EasySwoole

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image easyswoolexuesi2021/easyswoole:php8.2.8-alpine3.18-swoole5.0.3
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/php8/8.2.8/alpine/3.18/swoole/5.0.3/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le
          push: true
          tags: |
            easyswoolexuesi2021/easyswoole:php8.2.8-alpine3.18-swoole5.0.3
