name: Build Versioned Alpine Images for EasySwoole PHP 8.1

#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build_versioned_alpine_images:
    runs-on: ubuntu-22.04
    if: github.repository == 'xuesilf/easyswoole-docker'
    strategy:
      matrix:
        include:
          - php: 8.1.22
            alpine: 3.16
            swoole: "4.8.13"
          - php: 8.1.22
            alpine: 3.16
            swoole: "5.0.3"
          - php: 8.1.22
            alpine: 3.16
            swoole: "5.1.1"
          - php: 8.1.27
            alpine: 3.18
            swoole: "4.8.13"
          - php: 8.1.27
            alpine: 3.18
            swoole: "5.0.3"
          - php: 8.1.27
            alpine: 3.18
            swoole: "5.1.1"

    name: The Alpine Image For EasySwoole PHP-${{ matrix.php }} Swoole-${{ matrix.swoole }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image easyswoolexuesi2021/easyswoole:php${{ matrix.php }}-alpine${{ matrix.alpine }}-swoole${{ matrix.swoole }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/php8/${{ matrix.php }}/alpine/${{ matrix.alpine }}/swoole/${{ matrix.swoole }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            easyswoolexuesi2021/easyswoole:php${{ matrix.php }}-alpine${{ matrix.alpine }}-swoole${{ matrix.swoole }}
