name: Build Base Alpine Images for EasySwoole

#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build_base_alpine_images:
    runs-on: ubuntu-22.04
    if: github.repository == 'xuesilf/easyswoole-docker'
    name: The Base Alpine Image For EasySwoole
    strategy:
      matrix:
        include:
          - php-prefix: "7"
            php: "7.3.33"
            alpine: "3.12"
          - php-prefix: "7"
            php: "7.4.33"
            alpine: "3.15"
          - php-prefix: "8"
            php: "8.1.22"
            alpine: "3.16"
          - php-prefix: "8"
            php: "8.1.27"
            alpine: "3.18"
          - php-prefix: "8"
            php: "8.2.17"
            alpine: "3.19"
          - php-prefix: "8"
            php: "8.3.4"
            alpine: "3.19"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image easyswoolexuesi2021/php:${{ matrix.php }}-alpine${{ matrix.alpine }}-base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/php${{ matrix.php-prefix }}/${{ matrix.php }}/alpine/${{ matrix.alpine }}/base/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            easyswoolexuesi2021/php:${{ matrix.php }}-alpine${{ matrix.alpine }}-base
